# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mzhong <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/07/28 15:26:55 by mzhong            #+#    #+#              #
#    Updated: 2016/07/28 15:26:56 by mzhong           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

all: $(NAME)
	
$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) ft_display_file.c

clean:

fclean: clean
	rm $(NAME)